### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by Benjamin-beep** [arthaud/git-dumper#4] opened 2019-08-05 19:43 UTC
Hi, i am having a problem, maybe someone knows how to fix this:

Process FindObjectsWorker-28:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "git-dumper.py", line 108, in run
    result = self.do_task(task, *self.args)
  File "git-dumper.py", line 285, in do_task
    obj_file = dulwich.objects.ShaFile.from_path(abspath)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/objects.py", line 401, in from_path
    return cls.from_file(f)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/objects.py", line 407, in from_file
    obj = cls._parse_file(f)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/objects.py", line 382, in _parse_file
    obj._parse_object(map)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/objects.py", line 362, in _parse_object
    self.set_raw_string(_decompress(raw))
  File "/usr/local/lib/python3.6/dist-packages/dulwich/objects.py", line 84, in _decompress
    dcomped = dcomp.decompress(string)
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by arthaud** [comment] 2020-01-04 14:54
Hi @Benjamin-beep,

Do you still have the issue?
Could you provide us a way to reproduce it?

**Comment by evilboyajay** [comment] 2020-04-20 05:22
I got the same error at 
    dcomped = dcomp.decompress(string)

**Comment by vzamanillo** [comment] 2020-05-13 21:25
This can be caused by a response with status code 200 but with not a binary content like a WAF response or another (stackpath, cloudflare).

**Comment by amiralkizaru** [comment] 2020-05-19 04:32
@vzamanillo anyway around this ?

**Comment by vzamanillo** [comment] 2020-05-19 16:50
> @vzamanillo anyway around this ?

No way :/, the one and only solution is passing the headers to request.

**Comment by DashLt** [comment] 2020-11-15 20:45
This is caused by sites returning error pages with a 200 status code (incorrect, but it happens a lot). Fixed in #13.

**Comment by arthaud** [comment] 2021-02-21 21:56
This should be fixed by 7da1861375efcc20c9f2b96a4bd6a7e71d160d64

**Closed by arthaud** 2021-02-21 21:56 UTC
